version: '3.7'

services:
    db:
        image: mongo:5
        env_file: quickstart.env
        ports:
        -   27017:27017
    app:
        image: realsidsun/snippets-api:latest
        env_file: quickstart.env
        depends_on:
            - db
        ports:
        - 8080:8080
