resources:
  - name: ioctl-api-source
    type: git
    source:
      uri: git@github.com:Sid-Sun/ioctl-api.git
      branch: main
      private_key: ((repo_privkey))
  - name: ioctl-api-image
    type: registry-image
    icon: docker
    source:
      repository: ((registry_url))/((image_repo))/ioctl-api
      tag: latest
      username: ((registry_username))
      password: ((registry_password))

jobs:
  - name: build-and-push
    plan:
      - get: ioctl-api-source
        trigger: true
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
              tag: master
          inputs:
            - name: ioctl-api-source
          outputs:
            - name: image
          params:
            CONTEXT: ioctl-api-source
          run:
            path: build
      - task: tag-image
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine/git
          inputs:
            - name: ioctl-api-source
          outputs:
            - name: tags
          run:
            path: sh
            args:
              - -c
              - cd ioctl-api-source; git rev-parse --short HEAD > ../tags/tags
      - put: ioctl-api-image
        params:
          image: image/image.tar
          additional_tags: tags/tags
